package server

import (
	"log/slog"
	"net/http"
	"strings"
	"sync"
	"time"
)

type authRateLimiter struct {
	lastCleanup time.Time
	entries     map[string]*authRateLimitEntry
	mu          sync.Mutex
}

type authRateLimitEntry struct {
	lastSeen    time.Time
	lockedUntil time.Time
	tokens      float64
	failedCount int
}

func newAuthRateLimiter() *authRateLimiter {
	return &authRateLimiter{
		entries:     make(map[string]*authRateLimitEntry),
		mu:          sync.Mutex{},
		lastCleanup: time.Time{},
	}
}

func (l *authRateLimiter) allow(ip string, now time.Time) bool {
	if strings.TrimSpace(ip) == "" {
		return false
	}

	l.mu.Lock()
	defer l.mu.Unlock()

	l.cleanup(now)

	entry := l.ensureEntry(ip, now)
	if !entry.lockedUntil.IsZero() && entry.lockedUntil.After(now) {
		return false
	}

	if entry.tokens < 1 {
		return false
	}

	entry.tokens--
	entry.lastSeen = now

	return true
}

func (l *authRateLimiter) cleanup(now time.Time) {
	cleanupDue := l.lastCleanup.IsZero() || now.Sub(l.lastCleanup) >= authRateCleanupPeriod
	if !cleanupDue && len(l.entries) < authRateMaxEntries {
		return
	}

	cutoff := now.Add(-authRateEntryTTL)
	for ip, entry := range l.entries {
		if entry.lastSeen.Before(cutoff) && !entry.lockedUntil.After(now) {
			delete(l.entries, ip)
		}
	}

	l.evictOldestEntries()
	l.lastCleanup = now
}

func (l *authRateLimiter) evictOldestEntries() {
	for len(l.entries) >= authRateMaxEntries {
		delete(l.entries, l.oldestEntryIP())
	}
}

func (l *authRateLimiter) oldestEntryIP() string {
	var (
		oldestIP string
		oldest   time.Time
	)

	for ip, entry := range l.entries {
		if oldestIP == "" || entry.lastSeen.Before(oldest) {
			oldestIP, oldest = ip, entry.lastSeen
		}
	}

	return oldestIP
}

func (l *authRateLimiter) ensureEntry(ip string, now time.Time) *authRateLimitEntry {
	entry, ok := l.entries[ip]
	if !ok {
		entry = &authRateLimitEntry{
			lastSeen:    now,
			lockedUntil: time.Time{},
			tokens:      authRateMaxTokens,
			failedCount: 0,
		}
		l.entries[ip] = entry

		return entry
	}

	elapsed := now.Sub(entry.lastSeen).Seconds()
	if elapsed > 0 {
		entry.tokens += elapsed * authRateRefillPerSec
		if entry.tokens > authRateMaxTokens {
			entry.tokens = authRateMaxTokens
		}
	}

	entry.lastSeen = now

	return entry
}

func (l *authRateLimiter) recordFailure(ip string) {
	if strings.TrimSpace(ip) == "" {
		return
	}

	now := time.Now().UTC()

	l.mu.Lock()
	defer l.mu.Unlock()

	entry := l.ensureEntry(ip, now)

	entry.failedCount++
	if entry.failedCount >= authFailureThreshold {
		entry.failedCount = 0
		entry.lockedUntil = now.Add(authLockDuration)
	}
}

func (l *authRateLimiter) recordSuccess(ip string) {
	if strings.TrimSpace(ip) == "" {
		return
	}

	now := time.Now().UTC()

	l.mu.Lock()
	defer l.mu.Unlock()

	entry := l.ensureEntry(ip, now)
	entry.failedCount = 0
	entry.lockedUntil = time.Time{}
}

func (a *App) withAuthRateLimit(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !a.authEnabled || !strings.HasPrefix(r.URL.Path, "/auth/") {
			next.ServeHTTP(w, r)

			return
		}

		now := time.Now().UTC()
		ip := requestRealIP(r)

		if !a.authRateLimiter.allow(ip, now) {
			//nolint:gosec // The request ID is generated by the server and contains no user-controlled data.
			slog.Warn("auth request throttled", "request_id", requestIDFromRequest(r))
			http.Error(w, "too many auth requests", http.StatusTooManyRequests)

			return
		}

		next.ServeHTTP(w, r)
	})
}

func (a *App) recordAuthFailure(r *http.Request) {
	if a.authRateLimiter == nil {
		return
	}

	a.authRateLimiter.recordFailure(requestRealIP(r))
}

func (a *App) recordAuthSuccess(r *http.Request) {
	if a.authRateLimiter == nil {
		return
	}

	a.authRateLimiter.recordSuccess(requestRealIP(r))
}
